version: 0.1.{build}
image: Visual Studio 2015
environment:
  STACK_ROOT: C:\sr\
  IV:
    secure: au7xZlSNdoqtLzQn+p5NQ4jf3yRtivPT8fJMAmY2wHK37keC3zh1YBjDOD1dHcQ4SStN82XDWux5FCkqW+R1Vg==
install:
- cmd: >-
    set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

    curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386

    7z x stack.zip stack.exe

    stack --no-terminal --install-ghc --arch i386 test --only-dependencies

cache: C:\sr\
build: off
test_script:
- cmd: stack --no-terminal --arch i386 test --haddock --no-haddock-deps --flag license-haskell:production

before_deploy:
- ps: $appPath = ./stack.exe --arch i386 path --local-install-root
- ps: $appPath = "${appPath}\bin"
- ps: $packagePath = "license-gen-${APPVEYOR_BUILD_VERSION}.zip"
- ps: 7z a "$packagePath" "${appPath}\*.dll"

artifacts:
  - path: "${packagePath}"
    name: license-gen

deploy:
  provider: FTP
  protocol: ftps
  host: 39.108.64.177
  username: sftp
  password:
    secure: A5H1VsmjLKBx6FqP0jhhYqm7CLeSaCGGM4TnCLZTGig=
  folder: license-gen/archieve
  artifact: license-gen
